### ISSUE TITLE
Edit help menu looks weird

### ISSUE THREAD

**Issue by etwasanderes2** [jnccd/Discord-Bot#4]
I ran `$edit help GifCommands`, the result was somewhat unreadable. I don't think it was supposed to be like that. (Or maybe I am just really bad at reading or it just looks bad on mobile)

**Comment by etwasanderes2** [comment]
It appears that there is missing whitespace after the Commands "signature", also the formatting looks messes up.

**Comment by niklasCarstensen** [comment]
The formatting looks normal to me. Can you add a screenshot?
![image](https://user-images.githubusercontent.com/19777592/101265634-59e0a680-3748-11eb-8373-271b9717b4f3.png)

**Comment by etwasanderes2** [comment]
![Screenshot_20201205-224144_Discord.jpg](https://user-images.githubusercontent.com/37774073/101265939-20f60100-374b-11eb-83f0-5aa06b915011.jpg)
Here's a screenshot, from the Android mobile app. It looks different from yours.

**Comment by niklasCarstensen** [comment]
I assume that is a bug in the discord android app then since mobile embeds _should_ look like in the desktop version.
